# Generated by Django 2.2.7 on 2019-11-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registeruser',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
