# Generated by Django 2.2.7 on 2019-12-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191129_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='confirm_passsword',
        ),
        migrations.RemoveField(
            model_name='registeruser',
            name='password',
        ),
    ]
