# Generated by Django 2.2.7 on 2019-12-03 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191201_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registeruser',
        ),
    ]
